version: 2.1

orbs:
  styra-orb: styra/cli@dev:0.0.5

workflows:
  version: 2.1
  check-workflow:
    jobs:
    - styra-orb/styra-policy-check:
        context: SystemID_cf8d422d77e943c4a09c75236cd1630f
